package com.usermanagement.events;

import java.time.Instant;
import java.util.UUID;

/**
 * What an {@link EventSink} receives. {@code id} is unique per message and should be used by
 * consumers for de-duplication, since delivery is at-least-once.
 *
 * @param stream  {@link Streams#DOMAIN_EVENTS} or {@link Streams#AUDIT}
 * @param payload the message body as JSON
 */
public record OutboxMessage(UUID id, String stream, String eventType, String aggregateType, String aggregateId,
                            Instant occurredAt, String payload) {

    /**
     * The JSON envelope sent by the built-in sinks:
     * <pre>
     * {"id": "...", "stream": "audit", "type": "auth.login", "aggregateType": "user", "aggregateId": "...",
     *  "occurredAt": "...", "data": { ...payload... }}
     * </pre>
     * All values except the payload are generated by the service (UUIDs, constants, timestamps), so
     * they need no JSON escaping.
     */
    public String toEnvelopeJson() {
        return "{\"id\":\"" + id + "\""
                + ",\"stream\":\"" + stream + "\""
                + ",\"type\":\"" + eventType + "\""
                + ",\"aggregateType\":\"" + aggregateType + "\""
                + ",\"aggregateId\":\"" + aggregateId + "\""
                + ",\"occurredAt\":\"" + occurredAt + "\""
                + ",\"data\":" + payload + "}";
    }
}
